spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legend
    password: 1007
    username: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create



server:
  port: 8080
